version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: remitly_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: always
    image: amrchk/remitly-backend-app:latest
    container_name: remitly_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
